export const PROJECTS = {
  "performative-design": [
    {
      title: "Reincarnation of Violet",
      desc: "To design a way for people to embody and enact the outer appearance of a digital avatar.",
      imgSrc: require("../assets/images/ProjectTypes/reincarnationofViolet/reincarnation.png"),
      to: "reincarnation",
    },
    {
      title: "The Formless Emotions",
      desc: "To communicate the stories of water in any medium preferred.",
      imgSrc: require("../assets/images/ProjectTypes/theFormlessEmotions/theFormlessEmotion.png"),
      floadtRight: true,
      to: "formless-emotions",
    },
    {
      title: "Can skin starve for a touch?",
      desc: "To design a way to express the skin/world interface.",
      imgSrc: require("../assets/images/ProjectTypes/canSkin/canSkin.png"),
      to: "can-skin-starve-for-a-touch",
      marginTop: true,
    },
  ],
  "user-experience-design": [
    {
      title: "A Score To Find The Right People",
      desc: "Redesign the wealth and P2G score visualisation on a wealth intelligence platform.",
      subdesc: "Project Partner: WealthEngine, Altrata, London",
      subdescX: 0,
      subdescY: 5,
      imgSrc: require("../assets/images/ProjectTypes/weScoreRedesign/thumbnail.png"),
      to: "we-score-redesign",
      tags: ["SaaS", "B2B", "Data Visualisation"],
      // pdf: "/projects/project_boolean_protected.pdf",
      // titleNote: "Contact for password",
      position: "left",
      yOffset: 0,
    },
    {
      title: "Is United States, Not Texas",
      desc: "Design boolean logic conditions (AND/OR/NOT) into the Advanced search filters of a people intelligence platform.",
      subdesc: "Project Partner: Altrata, London",
      subdescX: 0,
      subdescY: 5,
      imgSrc: require("../assets/images/ProjectTypes/usNotTexas/thumbnail.png"),
      to: "us-not-texas",
      tags: ["Enterprise UX", "SaaS", "B2B"],
      // pdf: "/projects/project_boolean_protected.pdf",
      // titleNote: "Contact for password",
      position: "right",
      yOffset: -175,
    },
    {
      title: "Sharing Codes",
      desc: "Design a way to take advantage of other peoples’ digital transactions without them knowing.",
      subdesc: "Project Partner: IBM, London",
      subdescX: 0,
      subdescY: 5,
      imgSrc: require("../assets/images/ProjectTypes/justNameless/justNameless.png"),
      to: "sharing-codes",
      tags: ["Speculative", "Consumer", "Service Design"],
      position: "left",
      yOffset: 0,
    },
    {
      title: "The Yellow Juice",
      desc: "Design a digital/physical marketplace for the buying and selling of human bodily fluids that prioritises trust.",
      subdesc: "Project Partner: Gumtree, London",
      subdescX: 0,
      subdescY: 5,
      imgSrc: require("../assets/images/ProjectTypes/yellowJuice/yellowJuice.png"),
      to: "the-yellow-juice",
      tags: ["Speculative", "Marketplace", "Service Design"],
      position: "right",
      yOffset: -175,
    },
  ],
};
